language: java
jdk:
- openjdk8

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew build
      
notifications:
  email: false

# if releases are deployed on every commit (not only on tags, deploy.on.tags=false), a tag is needed nevertheless.
# this creates a custom tag containing a timestamp, as Travis CI would tag it like "untagged-RANDOMHEX"
before_deploy:
  - git config --local user.name "Marc Kohaupt (Travis CI)"
  - git config --local user.email "debuglevel@gmail.com"
  - git tag "$(date +'%Y-%m-%d_%H-%M-%S')_$(git log --format=%h -1)"
  
deploy:
  - provider: releases
    api_key:
      secure: txPqR2Wj96buxGxm0bUIYhE0/p8R740pOunvHOs6i4E1DtS0D4rJARTM3MSRgeda7rhDMsjEdog9DOhBXT/COmhv9XN7KR/WvjhAJFmfdHoqvSBPPTmW9BbZQirpYxb0VrWbtygHAO9bAYJPN+XNm0mST22p+Pdv1LyZvGnQJK04SV+ItKh0G3aQKg3Q4I5o79a0eyRgY6WmyadPsM26W+cgQ8ah6GpSzmZkdbByC030/QG3JhPjvp0ku1B6klBiLSSzpA7BjjiTrNpvLNbXBFyDtD8ehrg77zPpnaOmChqwgYvIEaqe7mwz4sHYCc6f/ce6sHFFfCeUbbZqCe58tAmZKglljt7ZyzT/+8MuYuSm8/QS2IB/8kDrYuTDYvIIXPHlVjsWUhI5zpKfxhbhvTy/PO7WhVVPUQxjuMd4k/6b5ixCoSsJ/weYhZ8h21QNQH41HLaQ8VSMkE30c1razFCh+0IOzGGESDjTJ5eisdFKKg670ZolCZMQHtZ/avO39c3S06QiUTnCrELiGuPc/COTJR9On5B4p63S3eYWnfu2ak0+u31W72QmY3Bo+g7SIw/FkSOOBIPuI5XwlvM5HUU/6NBnDGhGRLl+bZhaevfrgzNwvo7yM9/X+/kHDh4hHPHpIcJRxfNgXwFZVlkX1VQctBIZtm6KIsh8xSar/1k=
    file_glob: true
    file: "**/build/libs/*-all.jar"
    skip_cleanup: true
    # only deploy on certain conditions: https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A
    on:
      # only deploy commits of "master" branch
      branch: master
      # true: only deploy release if commit is not tagged
      # false: only deploy release if commit is tagged
      # if "tags" condition is present, the "branch" condition is ignored
      # if "tags" condition is not present, "branch" condition is considered
      #tags: false
  - provider: heroku
    api_key:
      secure: fZDxKNSJFAG4hb8xBDgIETScpU2XEGOAM5RvcUX4hOpKquNg/jOaAP4htihNGhbBQXwFEI89gexWcAYYYU6nw5pMUbs7cXB2v0ewtntaAEQiSgq9iBRuJExpEJIg7K0ArTwju3JDWngMczHMPZo0XJmkHm7zK+10YfZoB+QwA6ZUKW6wx3WdfMWOqXWAuB7UCVRUZnlYJ2yPyWKxh8dzqLKt/gTLj+YBsXoAUxlaQBWt9ssuvJ34i7tMkN2m+mJ8ewVZ+BcDH+JIUBn0M0XbXsdIr7Sl9996Y5dfMv/g8LRyMbZC0awx7rwLw1ysELrWSgMHoWJZ1ym6SfsU64DWY5c1lqmpBxL39jqeUUEn/AQfvPkTOlM0stoHilO82aWwFOo8hd9DT6Yg1h02Uzpb+3EAZG3xYN+qcbIJEYmiaIc1YaLs+Mmdo4D3mc5IzCaqbjrEY+JG6CvOpXR2FZMWuMBoERZaTDdU/qaYf7llfvHGON+f+Zo2cRv4uBp0kcaAFUSpicfr+YuxnAXNh7+cyMtcaBfcaCO434HQ/ngeLjrvpan29scNvV3MzaUKszVVQgV5KVyIYWNKkdV8y1Sbrm47aUpgjYWPprADvXjOCmMBZ2n52UGiehNvMLpdchvV1kK02M7toNUh40R6NYTy+mClhEoXEjfycwmxO9xsaIo=
    app: greeting-microservice
    on:
      branch: master